### ISSUE TITLE
whether this project can be applied to our own data?

### ISSUE THREAD

**Issue by ktxu1224** [tkwoo/StereoVisionforADAS#1]
Hello, thank for your code sharing.  But I wonder whether this code can be applied to our own data? Because I have seen from the file in StereoVisionforADAS that other data are not support. Could you tell the reason and what files needed to be modify to make it suitable for own data if it can? Please, thx!

**Comment by tkwoo** [comment]
This project is really strongly dependent on camera parameters because of stereo vision & geometry based computation.
You can apply to your data ( ZED or other stereo cameras ) if stereo calibration is accurate.

- Add your dataset parameters at this Init function.
 https://github.com/tkwoo/StereoVisionforADAS/blob/06e53c751f6053c7a2d169814f0e605585809083/StereoVisionForADAS.cpp#L10

I also tested on ZED stereo camera. but It was not quite accurate, not satisfied.
https://youtu.be/cTa0d5G788o

**Comment by ktxu1224** [comment]
@tkwoo ok ok, thx for replying! But I also wonder whether there are some materials or papers about the priciple of this algorithm ? And the sensors this algorithm used are just two monocular camera?  Thx

**Comment by tkwoo** [comment]
@ktxu1224 
I uploaded my presentation file.
https://www.slideshare.net/TaeKangWoo/stixel-based-real-time-object-detection-for-adas-using-surface-normal
For understanding, stereo vision basic theory is needed. (epipolar constraint, stereo calibration and stereo matching)

**Comment by ktxu1224** [comment]
@tkwoo Thank you a lot!
